# Generated by Django 5.2.12 on 2026-06-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='author',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='books',
            name='description',
        ),
        migrations.RemoveField(
            model_name='books',
            name='id',
        ),
        migrations.RemoveField(
            model_name='books',
            name='image',
        ),
        migrations.RemoveField(
            model_name='books',
            name='name',
        ),
        migrations.AddField(
            model_name='books',
            name='authors',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='books',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='books',
            name='book_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='books',
            name='image_url',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='books',
            name='isbn',
            field=models.TextField(default='0000000000'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='isbn13',
            field=models.TextField(default='0000000000'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='ratings_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='books',
            name='ratings_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='books',
            name='ratings_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='books',
            name='ratings_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='books',
            name='ratings_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='books',
            name='ratings_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='reviews_count',
            field=models.IntegerField(default=0),
        ),
    ]
