# Generated by Django 5.2.12 on 2026-06-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_author_books_title_remove_books_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodreadsUser',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
