# Generated by Django 5.2.12 on 2026-06-23 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_shelf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='reviews_count',
        ),
    ]
